# Generated by Django 5.2.8 on 2026-03-05 20:17

import urllib.request
from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.core.files.base import ContentFile

def download_image(url):
    """
    Descarga una imagen desde una URL y retorna su contenido en bytes.
    Incluye un User-Agent para evitar bloqueos (Error 403) de algunos servidores.
    """
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response:
            if response.status == 200:
                return response.read()
    except Exception as e:
        print(f"\n[Advertencia] No se pudo descargar la imagen {url}: {e}")
    return None

def create_initial_users(apps, schema_editor):
    CustomUser = apps.get_model('users_service', 'CustomUser')

    # Lista de usuarios reales solicitados
    users = [

        # User host for testing (don't erase) 
        ("Julian", True),

        # User guest for testing (don't erase) 
        ("Juan", False), 

        ("Pablo", False), ("Camila", False),
        ("Valentina", True), ("Andres", False), ("Sebastian", False), ("Mateo", True),
        ("Laura", False), ("Sofia", False), ("Daniel", False), ("Maria", True),
        ("Diego", False), ("Nicolas", False), ("Sara", True), ("Carolina", False),
        ("Jorge", False), ("Felipe", False), ("Lucia", True), ("Natalia", False),
    ]

    # Número base para generar teléfonos únicos y válidos para Colombia (+57)
    base_phone = 3001000000

    for i, (name, is_host) in enumerate(users):
        username = name.lower()
        email = f"{username}@correo.com"
        raw_password = f"{username}colombianstay" 
        phone = f"+57{base_phone + i}" # Ej: +573001000000, +573001000001...

        # 1. Instanciamos el usuario sin guardarlo en la base de datos todavía
        user = CustomUser(
            username=username,
            email=email,
            is_host=is_host,
            first_name=name,  
            phone_number=phone, # Obligatorio por tu modelo anterior
            password=make_password(raw_password)
        )
        
        # 2. Lógica para descargar la imagen de perfil
        url = f"https://api.dicebear.com/8.x/notionists/png?seed={username}"
        
        image_content = download_image(url)
        
        # 3. Si la descarga fue exitosa, la adjuntamos al campo ImageField
        if image_content:
            file_name = f"{username}_avatar.png"
            # save=False evita que haga un INSERT prematuro en la base de datos
            user.profile_picture.save(file_name, ContentFile(image_content), save=False)

        # 4. Guardamos el usuario con todos sus datos y su imagen
        user.save()


def delete_initial_users(apps, schema_editor):
    User = apps.get_model('users_service', 'CustomUser')
    nombres = [
        "julian", "juan", "pablo", "camila", "valentina", "andres",
        "sebastian", "mateo", "laura", "sofia", "daniel", "maria",
        "diego", "nicolas", "sara", "carolina", "jorge", "felipe",
        "lucia", "natalia"
    ]
    # Al eliminar los usuarios, Django eliminará automáticamente 
    # los archivos de imagen si tienes configurado un "cleanup", 
    # de lo contrario quedarán en tu carpeta /media/users/
    User.objects.filter(username__in=nombres).delete()

class Migration(migrations.Migration):

    dependencies = [
        # IMPORTANTE: Asegúrate de que esta dependencia apunte a la 
        # migración exacta donde creaste/modificaste el modelo CustomUser
        ('users_service', '0001_basemodel'), 
    ]

    operations = [
        migrations.RunPython(create_initial_users, delete_initial_users),
    ]