# Generated by Django 5.2.8 on 2026-03-05 20:17

from django.db import migrations
from users_service.models import CustomUser

def create_initial_users(apps, schema_editor):
    # Lista de usuarios reales solicitados
    users = [
        ("Julian", True),
        ("Juan", False),
        ("Pablo", False),
        ("Camila", False),
        ("Valentina", True),
        ("Andres", False),
        ("Sebastian", False),
        ("Mateo", True),
        ("Laura", False),
        ("Sofia", False),
        ("Daniel", False),
        ("Maria", True),
        ("Diego", False),
        ("Nicolas", False),
        ("Sara", True),
        ("Carolina", False),
        ("Jorge", False),
        ("Felipe", False),
        ("Lucia", True),
        ("Natalia", False),
    ]

    for name, is_host in users:
        username = name.lower()
        email = f"{username}@correo.com"
        password = f"{username}colombianstay" # La contraseña es el nombre en minúscula + colombianstay

        user = CustomUser(
            username=username,
            email=email,
            is_host=is_host,
            first_name=name  # opcional, por si quieres guardar el nombre
        )
        user.set_password(password)
        user.save()


def delete_initial_users(apps, schema_editor):
    User = apps.get_model('users_service', 'CustomUser')
    nombres = [
        "julian", "juan", "pablo", "camila", "valentina", "andres",
        "sebastian", "mateo", "laura", "sofia", "daniel", "maria",
        "diego", "nicolas", "sara", "carolina", "jorge", "felipe",
        "lucia", "natalia"
    ]
    User.objects.filter(username__in=nombres).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users_service', '0001_basemodel'),
    ]

    operations = [
        migrations.RunPython(create_initial_users, delete_initial_users),
    ]
