# Generated by Django 5.2.8 on 2026-04-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users_service', '0002_mockUsers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_as_contact',
            field=models.BooleanField(default=False, help_text='Establish the email to share'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('email_as_contact', False), ('is_host', True), _connector='OR'), name='email_contact_available_only_if_is_host'),
        ),
    ]
