# Generated by Django 5.2.8 on 2026-04-27 22:51

import random

from django.db import migrations


def randomize_host_contact_email(apps, schema_editor):

    CustomUser = apps.get_model('users_service', 'CustomUser')

    hosts = CustomUser.objects.filter(is_host=True)

    for user in hosts:
        user.email_as_contact = random.choice([True, False])
        user.save()

def reverse_randomize(apps, schema_editor):

    CustomUser = apps.get_model('users_service', 'CustomUser')
    
    CustomUser.objects.all().update(email_as_contact=False)

class Migration(migrations.Migration):

    dependencies = [
        ('users_service', '0003_basemodel'),
    ]

    operations = [
        migrations.RunPython(randomize_host_contact_email, reverse_randomize),
    ]
