# Generated by Django 5.2.8 on 2025-12-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('accomodationid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('idregion', models.IntegerField()),
                ('iddepartment', models.IntegerField()),
                ('idmunicipality', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('pricepernight', models.IntegerField()),
                ('maxguests', models.IntegerField()),
            ],
            options={
                'db_table': 'accomodation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('idregion', models.IntegerField()),
                ('iddepartment', models.IntegerField()),
                ('idmunicipality', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='namemunicipal', max_length=40)),
            ],
            options={
                'db_table': 'municipality',
                'managed': False,
            },
        ),
    ]
