# Generated by Django 5.2.8 on 2025-12-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='namedeparment', max_length=40)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('accomodationid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('pricepernight', models.IntegerField()),
                ('maxguests', models.IntegerField()),
            ],
            options={
                'db_table': 'accomodation',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('municipalityid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='namemunicipal', max_length=40)),
            ],
            options={
                'db_table': 'municipality',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nameregion', max_length=40)),
            ],
            options={
                'db_table': 'region',
            },
        ),
    ]
