# Generated by Django 5.2.8 on 2025-12-05 22:05

from django.db import migrations

def fill_location_data(apps, schema_editor):
    Region = apps.get_model('listings_service', 'Region')
    Department = apps.get_model('listings_service', 'Department')
    Municipality = apps.get_model('listings_service', 'Municipality')

    colombia_data = {
        "Caribe": {
            "Atlántico": ["Barranquilla", "Soledad", "Puerto Colombia"],
            "Bolívar": ["Cartagena", "Turbaco"],
            "Magdalena": ["Santa Marta"],
            "Córdoba": ["Montería"],
            "Sucre": ["Sincelejo"],
            "La Guajira": ["Riohacha"],
        },
        "Andina": {
            "Cundinamarca": ["Bogotá", "Zipaquirá", "La Calera"],
            "Antioquia": ["Medellín", "Envigado", "Guatapé"],
            "Santander": ["Bucaramanga", "San Gil"],
            "Boyacá": ["Tunja", "Villa de Leyva"],
            "Risaralda": ["Pereira"],
            "Quindío": ["Armenia"],
            "Caldas": ["Manizales"],
        },
        "Pacífica": {
            "Valle del Cauca": ["Cali", "Buenaventura", "Palmira"],
            "Chocó": ["Quibdó"],
        },
        "Orinoquía": {
            "Meta": ["Villavicencio"],
            "Arauca": ["Arauca"],
        },
        "Amazónica": {
            "Caquetá": ["Florencia"],
            "Amazonas": ["Leticia"],
        },
        "Insular": {
            "San Andrés y Providencia": ["San Andrés", "Providencia"],
        }
    }
    
    for region_nombre, departamentos in colombia_data.items():
        region_obj, _ = Region.objects.get_or_create(name=region_nombre)
        for depto_nombre, municipios in departamentos.items():
            depto_obj, _ = Department.objects.get_or_create(
                name=depto_nombre,
                region=region_obj
            )
            for municipio_nombre in municipios:
                Municipality.objects.get_or_create(
                    name=municipio_nombre,
                    department=depto_obj
                )

def unfill_location_data(apps, schema_editor):
    Region = apps.get_model('listings_service', 'Region')

    Region.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('listings_service', '0002_basemodel'),
    ]

    operations = [
        migrations.RunPython(fill_location_data,unfill_location_data),
    ]
