# Generated by Django 5.2.8 on 2025-12-05 22:05

import json
from pathlib import Path

from django.db import migrations
from django.contrib.gis.geos import GEOSGeometry

def fill_location_data(apps, schema_editor):
    Region = apps.get_model('listings_service', 'Region')
    Department = apps.get_model('listings_service', 'Department')
    Municipality = apps.get_model('listings_service', 'Municipality')

    colombia_data = {
        "Caribe": {
            "Atlántico": ["Barranquilla", "Soledad", "Puerto Colombia"],
            "Bolívar": ["Cartagena", "Turbaco"],
            "Magdalena": ["Santa Marta"],
            "Córdoba": ["Montería"],
            "Sucre": ["Sincelejo"],
            "La Guajira": ["Riohacha"],
        },
        "Andina": {
            "Cundinamarca": ["Bogotá", "Zipaquirá", "La Calera"],
            "Antioquia": ["Medellín", "Envigado", "Guatapé"],
            "Santander": ["Bucaramanga", "San Gil"],
            "Boyacá": ["Tunja", "Villa de Leyva"],
            "Risaralda": ["Pereira"],
            "Quindío": ["Armenia"],
            "Caldas": ["Manizales"],
        },
        "Pacífica": {
            "Valle del Cauca": ["Cali", "Buenaventura", "Palmira"],
            "Chocó": ["Quibdó"],
        },
        "Orinoquía": {
            "Meta": ["Villavicencio"],
            "Arauca": ["Arauca"],
        },
        "Amazónica": {
            "Caquetá": ["Florencia"],
            "Amazonas": ["Leticia"],
        },
        "Insular": {
            "San Andrés y Providencia": ["San Andrés", "Providencia"],
        }
    }
    
    BASE_DIR = Path(__file__).resolve().parent.parent

    geojson_path = BASE_DIR / 'data' / 'municipios_colombia.geojson'

    with open(geojson_path, encoding='utf-8') as f:
        geojson_data = json.load(f)

    municipios_geo = {}

    for feature in geojson_data['features']:

        props = feature['properties']

        municipio_nombre = props.get('mpio_cnmbr')

        geometry = feature['geometry']

        if municipio_nombre and geometry:

            municipios_geo[municipio_nombre] = geometry

    for region_nombre, departamentos in colombia_data.items():
        region_obj, _ = Region.objects.get_or_create(name=region_nombre)
        for depto_nombre, municipios in departamentos.items():
            depto_obj, _ = Department.objects.get_or_create(
                name=depto_nombre,
                region=region_obj
            )
            for municipio_nombre in municipios:

                geometry = municipios_geo.get(municipio_nombre)

                if not geometry:
                    print(f'No geometry for {municipio_nombre}')
                    continue

                multipolygon = GEOSGeometry(
                    json.dumps(geometry),
                    srid=4326
                )

                Municipality.objects.get_or_create(
                    name=municipio_nombre,
                    department=depto_obj,
                    defaults={
                        'boundary': multipolygon
                    }
                )

def unfill_location_data(apps, schema_editor):
    Region = apps.get_model('listings_service', 'Region')

    Region.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('listings_service', '0002_basemodel'),
    ]

    operations = [
        migrations.RunPython(fill_location_data,unfill_location_data),
    ]
