# Generated by Django 5.2.8 on 2026-03-05 20:07

# Generated by Django 5.2.8 on 2025-12-11 07:21

from django.db import migrations
import random

def create_mock_listings(apps, schema_editor):
    Listing = apps.get_model('listings_service', 'Listing')
    User = apps.get_model('users_service', 'CustomUser')
    Municipality = apps.get_model('listings_service', 'Municipality')

    # Hosts
    hosts = list(User.objects.filter(is_host=True))

    # Si no hay municipios, la migración no puede crear listings
    municipalities = list(Municipality.objects.all())
    if not municipalities or not hosts:
        list(Municipality.objects.all())
        return

    titles = [
        "Casa Campestre Relax",
        "Apartamento Moderno en el Centro",
        "Cabaña Rústica Eco Natural",
        "Loft Minimalista Urbano",
        "Casa con Piscina Privada",
        "Apartamento Frente al Mar",
        "Cabaña Romántica Bosque Alto",
        "Mini Estudio Acogedor",
        "Penthouse de Lujo Panorámico",
        "Casa Colonial Restaurada",
        "Villa Familiar con Jardín",
        "Eco-Lodge Montaña Verde",
    ]

    descriptions = [
        "Un espacio perfecto para descansar y disfrutar de la naturaleza.",
        "Hospedaje ideal para familias, cerca de restaurantes y comercios.",
        "Zona segura, excelente conectividad y diseño moderno.",
        "Cabaña ecológica construida con materiales sostenibles.",
        "Hermosa vista y ambiente tranquilo para desconectar totalmente.",
        "Amplios espacios, luz natural y ubicación estratégica.",
    ]

    property_types = ["House", "Apartment", "Cabin", "Loft", "Studio"]

    # Crear 12 listings
    for i in range(12):
        Listing.objects.create(
            owner=random.choice(hosts),
            municipality=random.choice(municipalities),
            title=titles[i],
            description=random.choice(descriptions),
            bedrooms=random.randint(1, 5),
            bathrooms=random.randint(1, 3),
            locationdesc="Ubicación cercana a puntos de interés turísticos y comerciales.",
            addresstext=f"Calle {random.randint(1, 100)} # {random.randint(1,50)}-{random.randint(1,50)}",
            propertytype=random.choice(property_types),
            pricepernight=random.randint(80000, 500000),
            maxguests=random.randint(2, 10),
        )


def delete_mock_listings(apps, schema_editor):
    Listing = apps.get_model('listings_service', 'Listing')
    titles = [
        "Casa Campestre Relax",
        "Apartamento Moderno en el Centro",
        "Cabaña Rústica Eco Natural",
        "Loft Minimalista Urbano",
        "Casa con Piscina Privada",
        "Apartamento Frente al Mar",
        "Cabaña Romántica Bosque Alto",
        "Mini Estudio Acogedor",
        "Penthouse de Lujo Panorámico",
        "Casa Colonial Restaurada",
        "Villa Familiar con Jardín",
        "Eco-Lodge Montaña Verde",
    ]
    Listing.objects.filter(title__in=titles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users_service', '0002_mockUsers'),
        ('listings_service', '0003_fillLocation'),
    ]

    operations = [
        migrations.RunPython(create_mock_listings, delete_mock_listings),
    ]