# Generated by Django 5.2.8 on 2026-03-27 20:36

import django.core.validators
import django.db.models.deletion
import listings_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings_service', '0004_mockListings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=listings_service.models.ListingImage.upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=listings_service.models.ListingImage.upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('is_main', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings_service.listing')),
            ],
            options={
                'db_table': 'image_accomodation',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('listing',), name='unique_main_image_per_listing')],
            },
        ),
    ]
