# Generated by Django 5.2.8 on 2026-03-27 21:51

from django.db import migrations

from django.core.files.base import ContentFile
import requests
import random

def download_image(url: str) -> ContentFile | None:
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        return ContentFile(response.content)
    except requests.RequestException:
        return None

def create_mock_images(apps, schema_editor):
    ListingImage = apps.get_model('listings_service', 'ListingImage')
    Listing = apps.get_model('listings_service', 'Listing')

    listings = list(Listing.objects.all())

    if not listings:
        return

    for listing in listings:

        # 🔹 Imagen principal
        url = f"https://picsum.photos/seed/main_{listing.accomodationid}/800/600"
        main_image_file = download_image(url)

        url = f"https://picsum.photos/seed/main_{listing.accomodationid}/300/300"
        thumb_image_file = download_image(url)

        if main_image_file:
            ListingImage.objects.create(
                listing=listing,
                image=ContentFile(main_image_file.read(), name=f"accomodation_main_{listing.accomodationid}.jpg"),
                thumbnail=ContentFile(thumb_image_file.read(), name=f"thumb_accomodation_main_{listing.accomodationid}.jpg"),
                is_main=True
            )

        # 🔹 Imágenes adicionales
        for i in range(random.randint(2, 3)):
            url = f"https://picsum.photos/seed/{listing.accomodationid}_{i}/800/600"
            image_file = download_image(url)

            if image_file:
                ListingImage.objects.create(
                    listing=listing,
                    image=ContentFile(image_file.read(), name=f"accomodation_{listing.accomodationid}_image_extra_{i}.jpg"),
                    is_main=False
                )


def delete_mock_images(apps, schema_editor):
    ListingImage = apps.get_model('listings_service', 'ListingImage')

    for img in ListingImage.objects.iterator():
        try:
            if img.image:
                img.image.delete(save=False)
            if img.thumbnail:
                img.thumbnail.delete(save=False)
        except Exception as e:
            print(f"Error eliminando archivo: {e}")

    ListingImage.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('listings_service', '0005_basemodel'),
    ]

    operations = [
        migrations.RunPython(create_mock_images, delete_mock_images),
    ]
