# Generated by Django 5.2.8 on 2026-04-29 20:47

from django.db import migrations
import random


COMMENTS = [
    "Excelente experiencia, volvería a reservar.",
    "Muy buen alojamiento y anfitrión amable.",
    "Lugar limpio y cómodo.",
    "Buena ubicación, aunque hubo detalles menores.",
    "Experiencia aceptable.",
    "Muy recomendado.",
    "Todo salió perfecto.",
    "El alojamiento cumplió expectativas.",
    "Gran estancia, excelente atención.",
    "Podría mejorar algunos aspectos."
]


def seed_ratings(apps, schema_editor):
    Booking = apps.get_model('booking_service', 'Booking')
    Rating = apps.get_model('rating_service', 'Rating')

    completed_bookings = Booking.objects.filter(status='completed')

    ratings_to_create = []

    for booking in completed_bookings:

        # evitar duplicados si se corre varias veces
        if hasattr(booking, 'review'):
            continue

        if random.random() < 0.75:  # 75% dejan reseña

            score = random.choices(
                [1,2,3,4,5],
                weights=[3,7,15,30,45],
                k=1
            )[0]

            comment = random.choice(COMMENTS)

            ratings_to_create.append(
                Rating(
                    booking=booking,
                    rating=score,
                    comment=comment
                )
            )

    Rating.objects.bulk_create(ratings_to_create)


def remove_seed_ratings(apps, schema_editor):
    Rating = apps.get_model('rating_service', 'Rating')
    Rating.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rating_service', '0001_basemodel'),
        ('booking_service', '0002_mockBookings'),
    ]

    operations = [
        migrations.RunPython(seed_ratings, remove_seed_ratings),
    ]
