# Generated by Django 5.2.8 on 2026-05-16 22:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings_service', '0004_mockListings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('ACTIVE', 'Activa'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings_service.listing')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('booking_status_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('ACTIVE', 'Activa'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada')], default='PENDING', max_length=20)),
                ('desc_of_transaction', models.TextField(blank=True, null=True)),
                ('principal_actuator', models.CharField(blank=True, choices=[('GUEST', 'Huésped'), ('HOST', 'Anfitrión')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking_service.booking')),
            ],
            options={
                'db_table': 'booking_status_history',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'check_in_date', 'check_out_date'], name='booking_listing_b8e4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest', 'actual_status'], name='booking_guest_i_421957_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_date__gt', models.F('check_in_date'))), name='booking_check_out_after_check_in'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_guests__gte', 1)), name='booking_guests_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='booking_total_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='bookingstatushistory',
            constraint=models.UniqueConstraint(fields=('booking', 'status'), name='unique_booking_status'),
        ),
        migrations.AddConstraint(
            model_name='bookingstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), models.Q(('desc_of_transaction__isnull', False), ('principal_actuator__isnull', False)), _connector='OR'), name='cancelled_requires_fields'),
        ),
    ]
