# Generated by Django 5.2.8 on 2026-03-05 20:07

from django.db import migrations
import random
from datetime import timedelta, date

from booking_service.models import calculate_total_price

def create_mock_bookings(apps, schema_editor):
    Booking = apps.get_model('booking_service', 'Booking')
    Listing = apps.get_model('listings_service', 'Listing')
    User = apps.get_model('users_service', 'CustomUser')
    BookingStatusHistory = apps.get_model('booking_service', 'BookingStatusHistory')

    listings = list(Listing.objects.all())
    guests = list(User.objects.filter(is_host=False))

    if not listings or not guests:
        return

    status_flow = [
        "PENDING",
        "CONFIRMED",
        "ACTIVE",
        "COMPLETED"
    ]

    for _ in range(80):
        listing = random.choice(listings)
        guest = random.choice(guests)

        start_date = date.today() + timedelta(days=random.randint(1, 60))
        nights = random.randint(1, 10)
        end_date = start_date + timedelta(days=nights)

        final_status = random.choice([
            "PENDING",
            "CONFIRMED",
            "ACTIVE",
            "COMPLETED",
            "CANCELLED"
        ])

        # Crear booking SIEMPRE en PENDING primero
        booking = Booking.objects.create(
            listing=listing,
            guest=guest,
            check_in_date=start_date,
            check_out_date=end_date,
            number_of_guests=random.randint(1, listing.maxguests),
            total_price= calculate_total_price(listing.pricepernight, nights),
            actual_status="PENDING"
        )

        # Construir historial según estado final
        current_flow = []

        if final_status == "PENDING":
            continue

        elif final_status == "CONFIRMED":
            current_flow = ["CONFIRMED"]

        elif final_status == "ACTIVE":
            current_flow = ["CONFIRMED", "ACTIVE"]

        elif final_status == "COMPLETED":
            current_flow = ["CONFIRMED", "ACTIVE", "COMPLETED"]

        elif final_status == "CANCELLED":
            # cancelar desde CONFIRMED o ACTIVE
            if random.choice([True, False]):
                current_flow = ["CONFIRMED", "CANCELLED"]
            else:
                current_flow = ["CONFIRMED", "ACTIVE", "CANCELLED"]

        # Crear historial manual (sin usar update_status para evitar lógica extra)
        for status in current_flow:
            if status == "CANCELLED":
                BookingStatusHistory.objects.create(
                    booking=booking,
                    status=status,
                    desc_of_transaction="Cancelación de prueba",
                    principal_actuator=random.choice(["GUEST", "HOST"])
                )
            else:
                BookingStatusHistory.objects.create(
                    booking=booking,
                    status=status
                )

        # Actualizar estado final del booking
        booking.actual_status = final_status
        booking.save(update_fields=["actual_status"])


def delete_mock_bookings(apps, schema_editor):
    Booking = apps.get_model('booking_service', 'Booking')
    Booking.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('listings_service', '0004_mockListings'),
        ('users_service', '0004_mockUsers'),
        ('booking_service', '0001_basemodel'),
    ]

    operations = [
        migrations.RunPython(create_mock_bookings, delete_mock_bookings),
    ]