# Generated by Django 5.2.8 on 2026-03-05 20:07

from django.db import migrations

import random
from datetime import timedelta, date

def create_mock_bookings(apps, schema_editor):
    Booking = apps.get_model('booking_service', 'Booking')
    Listing = apps.get_model('listings_service', 'Listing')
    User = apps.get_model('users_service', 'CustomUser')

    listings = list(Listing.objects.all())
    guests = list(User.objects.filter(is_host=False))  # solo huéspedes

    if not listings or not guests:
        return
    
    status_options = ['pending', 'confirmed', 'completed', 'cancelled']

    # Crear 80 reservas mock
    for _ in range(80):
        listing = random.choice(listings)
        guest = random.choice(guests)

        # Fechas: check-in entre hoy y 60 días adelante
        start_date = date.today() + timedelta(days=random.randint(1, 60))
        nights = random.randint(1, 10)
        end_date = start_date + timedelta(days=nights)

        # Precio total basado en precio por noche del listing
        total_price = listing.pricepernight * nights

        Booking.objects.create(
            listing=listing,
            guest=guest,
            check_in_date=start_date,
            check_out_date=end_date,
            number_of_guests=random.randint(1, listing.maxguests),
            total_price=total_price,
            status=random.choice(status_options)
        )


def delete_mock_bookings(apps, schema_editor):
    Booking = apps.get_model('booking_service', 'Booking')
    Booking.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('listings_service', '0004_mockListings'),
        ('users_service', '0002_mockUsers'),
        ('booking_service', '0001_basemodel'),
    ]

    operations = [
        migrations.RunPython(create_mock_bookings, delete_mock_bookings),
    ]